### ISSUE TITLE
Remover dependência de `Otc.DomainBase.Exceptions`

### ISSUE THREAD

**Issue by matheusneder** [OleConsignado/otc-pdf-template#3]
Remover dependência de `Otc.DomainBase.Exceptions` e remodelar as exceções sem utilizar `CoreException` como base. Motivo: O propósito da `Otc.DomainBase.Exceptions.CoreException` e servir de base exclusivamente para exceções de negócio.

_Originally posted by @matheusneder in https://github.com/OleConsignado/otc-pdf-template/pull/2#issuecomment-423761099_

**Comment by HenriqueMaza** [comment]
Ajustado conforme solicitado
